contact_links:
  - name: WaspSlicer Manual and Support
    url: https://help.wasp3d.com/en/article/customer-support_2287/
    about: If you are not sure that what you are reporting is really a bug, please, consult the manual first.
  - name: WaspPrinters Forum
    url: https://forum.waspprinters.org/forum/waspslicer/
    about: Please get in touch on our WaspPrinters Community Forum! (Not an official support channel.)
    
blank_issues_enabled: false
